const norte = document.querySelector("#norte");

norte.addEventListener('click', () =>{
    Norte();
})

function limpa(){
    document.querySelector("#texto5").textContent = "";
    document.querySelector("#titulo5").textContent = "";
}

function Norte(){
    document.querySelector("#texto1").textContent = "A região norte tem uma densidade demográfica de 4,78 habitantes por quilômetro quadrado, com uma população absoluta de 18.430.980 habitantes (2019), é o estado com maior taxa de fecundidade do Brasil, com uma mortalidade de 6,8 óbitos para cada mil habitantes e um território de 3.853.676,948 quilômetros quadrados";
    document.querySelector("#texto2").textContent = "A região Norte é uma das áreas mais ricas em biodiversidade de espécies de plantas, animais e microorganismos do mundo, abrangendo a Floresta Amazônica, a maior floresta tropical do planeta. A região norte abriga diversas populações indígenas e tradicionais, como os ribeirinhos, quilombolas e seringueiros. Na região ainda acontecem os desmatamentos, que são causados pela expansão agrícola, explorações madeireiras ilegais e minerações que ainda ocorrem, apesar da região da floresta amazônica ser uma das mais importantes do mundo para a conservação da biodiversidade. Esta região possui uma grande quantidade de rios e bacias hidrográficas, incluindo o Rio Amazonas, desempenhando um papel importante nas comunidades da região, sejam elas de transporte, consumo, pesca e agricultura. O desmatamento na Amazônia está trazendo diversas mudanças climáticas no globo e também o aumento da frequência de enchentes e alagamentos na região norte.";
    document.querySelector("#texto3").textContent = "Nos últimos anos, em relação aos direitos, tivemos avanços significativos, sejam eles na demarcação de terras indígenas, fortalecimento da participação política pelos indígenas e políticas de inclusão social para os povos originários. Contudo, também tivemos problemas em relação à expansão agrícola, o aumento da violência contra os povos originários e o enfraquecimento das políticas ambientais."; //direitos
    document.querySelector("#texto4").textContent = "Na região norte os conflitos fundiários pela posse de terras ainda ocorrem pela falta de regularização fundiária, que possibilita a existência de conflitos entre diferentes grupos tentando ter posse de terras indígenas e áreas de conservação ambiental.";
    
    document.querySelector("#texto5").textContent = "A região norte do Brasil é a com a menor densidade demográfica. Isso ocorre por ser uma região mais pobre, que teve um fluxo migratório grande de pessoas de dentro e de fora do estado (como no caso dos venezuelanos que foram para lá), teve uma população que era contida no geral por indígenas, além da mata densa, presente ainda hoje. Ao longo dos anos também tivemos altas taxas de migração para fora da região norte. A região é mais propensa a ter alagamentos e enchentes por ser contida de matas e rios, por conta disso, fica difícil viajar de avião e carro pela região, tornando mais viável a viagem em barcos, lanchas e canoas, que pode levar dias.";
    document.querySelector("#titulo5").textContent = "Analise";
}
function Acre(){//V
    document.querySelector("#texto1").textContent = "A densidade demográfica do Acre é de 5,44 habitantes/km ², sendo o cálculo de 894.470 habitantes (2023) dividido pelo tamanho de 164.221,36 Km² do estado. O crescimento populacional desse estado é de 1,4% (2023). Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é que até a segunda metade do século XIX ele era povoado somente por indígenas e era pertencente à Bolívia e ao Peru, então somente em 1877 os primeiros imigrantes Nordestinos chegaram para ocupar o lugar. E o estado é o 25° em população e 15° em território.";//dados demograficos
    document.querySelector("#texto2").textContent = "Alguns dos aspectos socioambientais do Acre são a biodiversidade, o desmatamento (o Acre sofre muito desmatamento ilegal, o que prejudica sua população e a biodiversidade), as mudanças climáticas, o que é péssimo para as populações que dependem dos recursos naturais da região, recursos hídricos, pois o Acre é atravessado por importantes rios, como o Juruá, o Purus e o Acre, o que é ótimo para muitos aspectos do lugar e a groecologia, que consiste em práticas agroecológicas, que buscam conciliar a produção agrícola com a preservação ambiental e a sustentabilidade social. Algo muito importante também são os povos indígenas, o Acre é lar de diversas comunidades tradicionais, como povos indígenas, ribeirinhos e seringueiros, e reconheceu oficialmente algumas terras, como a Terra Indígena Mamoadate em 1993. Porém, apesar do reconhecimento oficial de diversas terras indígenas, as comunidades indígenas do estado ainda enfrentam ameaças à sua cultura e seus territórios.";
    document.querySelector("#texto3").textContent = "O Acre tem reconhecido diversas terras indígenas, porém, as comunidades ainda enfrentam ameaças a essas terras e a sua cultura, o estado tem tido avanços na saúde e educação e também tem enfrentado um grande aumento nos desmatamentos e queimadas ";
    document.querySelector("#texto4").textContent = "O Acre possui aproximadamente 72% do seu território com destinação fundiária, eliminando-se sobreposições entre categorias fundiárias. E, identifica-se 32% como Unidades de Conservação, apenas 15% de Terras Indígenas, 14% de imóveis privados e 11% de Projetos de Assentamentos. O estado possui quase metade do seu território protegido por lei.";
    
    limpa();
}

function Amapa(){//V
    document.querySelector("#texto1").textContent = "A densidade demográfica do Amapá é de 6,15 habitantes/km², sendo o cálculo de 877.613 habitantes (2021) dividido pelo tamanho de 142.814 km ² do estado. O crescimento populacional desse estado é de 0,51%(2021). Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é de que… o estado é o 25°(2021) em população e 18° em território."; //dados demográficos
    document.querySelector("#texto2").textContent = " O clima do Amapá é equatorial úmido caracterizado por altas temperaturas e umidade, o Amapá é composta por três vegetação a floresta amazônica que cobre a maior parte do Amapá, os manguezais, localizados em regiões de estuários e áreas inundadas periodicamente por maré, o terceiro e o último é o campinaranas é encontrado em vegetação entra a floresta amazônia e os campos abertos.  "; //Aspectos socioambientais
    document.querySelector("#texto3").textContent = "Desde janeiro, a Sepi possui uma formação colegiada, com quatro secretários adjuntos que representam as regiões os povos originários Wajãpi, Waiana, Galibi Marworno e Galibi Kali’na. A ação é parte do Plano de Governo para a proteção dos direitos individuais e coletivos."; //direitos
    document.querySelector("#texto4").textContent = "Até meados da década de 1940, a ocupação do espaço rural amapaense estava concentrada na região litorânea e ao longo das margens dos principais rios navegáveis, locais onde camponeses, ribeirinhos e comunidades tradicionais, dedicados ao extrativismo e à criação do gado, ocupavam terras, em sua maioria, em regimes de posses coletivas. Alguns poucos imóveis detinham escritura pública de propriedade concedida pelo estado do Pará."; //Questão fundiaria
   
    limpa();
}

function Amazonas(){//V
    document.querySelector("#texto1").textContent = "A densidade demográfica do Amazonas é de 2,69 habitantes/km ², sendo o cálculo de 4.207.714,00 habitantes (2020) dividido pelo tamanho de 1.559.167,889 km ² do estado. O crescimento populacional desse estado é de 1,6% (2019). Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é de que o estado é cheio de matas, facilitando alagamentos e dificultando o crescimento de cidades. E o estado é o 13° em população (2020) e o maior estado do Brasil."; //dados demográficos
    document.querySelector("#texto2").textContent = "O Amazonas contém a maior extensão da floresta amazônica dentro do Brasil. A floresta possui um papel vital na regulação do clima global, na biodiversidade e no fornecimento de serviços ecossistêmicos.O Amazonas é atravessado por várias bacias hidrográficas que fornecem água e habitat para diversas espécies de animais aquáticos que ali vivem, além de ser uma via de transporte importante para quem reside no Amazonas. No Amazonas também temos unidades de conservação de unidades extrativistas, reservas de desenvolvimento sustentável, parques nacionais e as terras indígenas. A região do Amazonas é considerada a região com a maior biodiversidade de espécies do planeta.Infelizmente o Amazonas vem enfrentando alguns problemas ambientais graves como desmatamento, queimadas, agropastoreio e a biopirataria, e estes problemas como um todo podem causar fenômenos graves no meio ambiente."; //Aspectos socioambientais
    document.querySelector("#texto3").textContent = "A floresta amazônica continua sendo desmatada e por conta do crescimento dos níveis de desmatamento, contaminação de rios e conflitos fundiários envolvendo as terras, fazem com que os indígenas sejam expulsos de suas terras. As aldeias indígenas na pandemia estavam passando por epidemias causadas pela negligência do governo com os cuidados aos povos indígenas."; //direitos
    document.querySelector("#texto4").textContent = "A questão fundiária no Amazonas envolve problemas como grilagem de terras, conflitos entre comunidades tradicionais e ocupação desordenada para atividades agropecuárias e exploração de recursos naturais."; //Questão fundiaria
    
    limpa();
}

function Rondonia(){ //V
    document.querySelector("#texto1").textContent = "A densidade demográfica de Rondônia é de 7,63 habitantes/km ², sendo o cálculo de 1.815.278 habitantes (2021) dividido pelo tamanho de 237.765,240 km ² do estado. O crescimento populacional desse estado é de 1,04% (2021). Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é de que boa parte dela deve-se, principalmente, ao fluxo migratório, o que também causa grande diversidade cultural. E o estado é o 23° em população e 13° em território."; //dados demográficos
    document.querySelector("#texto2").textContent = "As conseqüências mais marcantes podem resumidas em: ocupação espacial desordenada sem dotação de infra-estrutura; o desmatamento acelerado de quase 25% da floresta primária; a existência de três milhões de hectares de solos em processo de alteração; pastagens ociosas e capoeiras improdutivas; perda de biodiversidade; descaracterização das áreas protegidas; a apropriação das terras de populações tradicionais com conseqüentes desintegrações culturais, além do agravamento dos problemas sociais urbanos e baixa produtividade das explorações."; //Aspectos socioambientais
    document.querySelector("#texto3").textContent = "Os avanços de direitos em Rondônia incluem a criação do Plano Estadual de Educação em Direitos Humanos, o aumento da representatividade de mulheres e negros na política, os investimentos em infraestrutura e as políticas de incentivo à produção agroecológica. Já os retrocessos incluem o aumento do desmatamento e da grilagem de terras, a violência contra povos indígenas e quilombolas, a falta de investimento em políticas sociais básicas, como saúde e educação, e o aumento da violência urbana e da criminalidade."; //direitos
    document.querySelector("#texto4").textContent = "Em 2021, na cidade de Buritis, em Rondônia, participantes pediram desburocratização para permitir o avanço na regularização fundiária e em obras de infraestrutura no estado. Promovido pela Comissão de Agricultura e Reforma Agrária (CRA) do Senado, o debate, ocorrido  na Câmara Municipal, elencou uma série de medidas para que a região possa se desenvolver de forma sustentável. Fonte: Agência Senado"; //Questão fundiaria
    
    limpa();
}
function Roraima(){
    document.querySelector("#texto1").textContent = "A densidade demográfica de Roraima é de 2,90 habitantes/km ², sendo o cálculo de 652.713 habitantes (2021) dividido pelo tamanho de 224.300,64 km ² do estado. O crescimento populacional desse estado é de 4,2% (2020). Roraima é o segundo maior estado em crescimento populacional anual do país, por causa da migração dos Venezuelanos e o estado é o 27° em população e 14° em território."; //dados demográficos
    document.querySelector("#texto2").textContent = "Roraima é composto principalmente por dois biomas: a Amazônia e o Cerrado, possuindo várias unidades de conservação, que visam proteger a biodiversidade, os recursos naturais e os ecossistemas do estado. Roraima abriga uma rica diversidade biológica, com uma variedade de espécies de plantas, animais e aves. A região é conhecida por suas espécies endêmicas e possui uma importância significativa para a conservação da biodiversidade. O estado é atravessado por rios importantes, como o Rio Branco e o Rio Tacutu. Esses rios desempenham um papel crucial no abastecimento de água, na pesca e na regulação dos ecossistemas aquáticos do estado. Roraima enfrenta desafios ambientais, como o desmatamento ilegal, a expansão da fronteira agrícola, a mineração e os impactos resultantes do aumento da infraestrutura para o desenvolvimento regional. Esses desafios podem levar à perda de biodiversidade, à degradação dos recursos naturais e a outros impactos ambientais negativos."; //Aspectos socioambientais
    document.querySelector("#texto3").textContent = "Roraima abriga diversas comunidades indígenas, e o reconhecimento e respeito aos direitos dessas populações têm sido uma prioridade. Isso inclui a demarcação e proteção de terras indígenas, o respeito à cultura e aos modos de vida indígenas, além do acesso a serviços básicos, como saúde e educação. Também tivemos avanço nos direitos das mulheres e pessoas da comunidade LGBT+, graças aos esforços para promover a igualdade de gênero, independentemente de sua orientação sexual e gênero."; //direitos
    document.querySelector("#texto4").textContent = "Roraima possui uma significativa presença indígena e várias terras indígenas demarcadas. Essas terras são reconhecidas como áreas de posse e uso tradicional dos povos indígenas e visam garantir seus direitos territoriais e culturais. O estado enfrenta desafios relacionados a conflitos fundiários, especialmente em áreas de fronteira e regiões de ocupação recente. Esses conflitos envolvem disputas entre posseiros, grileiros, proprietários de terras e comunidades tradicionais. A regularização fundiária é um processo importante em Roraima, especialmente nas áreas rurais. O objetivo é garantir a segurança jurídica da posse e do uso das terras, buscando solucionar conflitos e promover o desenvolvimento sustentável."; //Questão fundiaria
   
    limpa();
}
function Tocantins(){
    document.querySelector("#texto1").textContent = "A densidade demográfica do Tocantins é de 1.497.277,621 (2014) habitantes/km ², sendo o cálculo de 1.497.000 habitantes (2014) dividido pelo tamanho de 277,621 km ² do estado. O crescimento populacional desse estado é de 1,13%. Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é por causa do fluxo migratório para o estado, que recebe migrantes de diferentes Regiões do país, o estado é o 24° em população e 10° em território."; //dados demográficos
    document.querySelector("#texto2").textContent = "O Tocantins abrange partes de dois importantes biomas brasileiros: o Cerrado e a Amazônia. Estes biomas guardam uma rica biodiversidade e eles têm papéis essenciais na regulação climática e na manutenção dos recursos hídricos. O estado possui diversas unidades de conservação e algumas unidades de conservação, como o Parque Nacional do Araguaia, a Estação Ecológica Serra Geral do Tocantins e o Parque Estadual do Jalapão. No Tocantins passam três importantes rios, o Rio Tocantins, o Rio Araguaia e o Rio Javaés que abastecem os moradores com água, peixes e disponibiliza o turismo. O Tocantins enfrenta todos os anos desmatamentos, a expansão agrícola, minerações, a contaminação dos recursos hídricos e a perda de biodiversidade, tornando necessário a preservação do Cerrado e da Amazônia. O Tocantins também abriga diversas comunidades indígenas e tradicionais, que têm um profundo conhecimento e vínculo com o meio ambiente. Essas comunidades desempenham um papel importante na preservação da cultura local e na conservação dos recursos naturais."; //Aspectos socioambientais
    document.querySelector("#texto3").textContent = "No Tocantins tivemos nos últimos anos um melhor acesso à educação, graças aos esforços do estado da região para melhorar a infraestrutura das escolas. No Tocantins também tivemos avanços nas demarcação de terras de comunidades indígenas, graças aos esforços para preservação da cultura dos povos originários, além do avanço nos direitos das mulheres e pessoas da comunidade LGBT+."; //direitos
    document.querySelector("#texto4").textContent = "Em Tocantins a questão fundiária está passando por disputas e conflitos relacionados à posse e titulação de terras, especialmente em áreas rurais. O estado também abriga diversas comunidades indígenas em territórios tradicionais que possuem proteção especial para preservar sua cultura, modos de vida e direitos. Os conflitos causados pela posse de terras envolvem posseiros, grileiros, proprietários rurais e comunidades tradicionais, gerando tensões e demandas por soluções por parte das autoridades competentes."; //Questão fundiaria
   
    limpa();
}
function Para(){//V
    document.querySelector("#texto1").textContent = "A densidade demográfica do Pará é de 6,91 habitantes/km ², sendo o cálculo de 8 690 745 habitantes (2020) dividido pelo tamanho de 1.248.000 km ² do estado. O crescimento 			populacional desse estado é de 2.1%. Uma curiosidade sobre o porquê do estado ter essa população distribuída desse jeito é de que o Pará tem uma forte contribuição de povos descendentes de imigrantes, e no estado vivem cerca de 31 etnias indígenas. E o estado é o 9° em população e 2° em território";
    document.querySelector("#texto2").textContent = "A hidrografia do Pará é marcada pelos rios da Bacia Amazônica. O próprio Rio Amazonas passa pelo estado e deságua no Oceano Atlântico na Ilha do Marajó. Os principais afluentes do Amazonas em território paraense são: o Tapajós, Xingu, Curuá, Trombetas e Nhamundá. Os povos Indígenas: O Pará é lar de diversas comunidades indígenas, que desempenham um papel fundamental na conservação da floresta e na preservação de suas tradições culturais. No entanto, muitas dessas comunidades enfrentam desafios, como a invasão de terras, conflitos com madeireiros ilegais e a falta de acesso a serviços básicos, como saúde e educação.";
    document.querySelector("#texto3").textContent = "No Pará, houve avanços significativos na conquista e garantia de direitos. Destacam-se os avanços relacionados aos direitos dos povos indígenas e das comunidades tradicionais, igualdade de gênero e combate à discriminação racial. Foram realizados esforços para demarcar e proteger terras indígenas, regularizar territórios de comunidades tradicionais, promover a igualdade de oportunidades para as mulheres e implementar políticas de combate à discriminação racial. No entanto, ainda existem desafios a serem enfrentados para garantir plenamente esses direitos e superar desigualdades existentes";
    document.querySelector("#texto4").textContent = "A questão fundiária no Pará envolve conflitos de posse e uso da terra, como grilagem e desmatamento ilegal, além de disputas entre diferentes grupos de interesses. Isso resulta em concentração fundiária, desmatamento e exclusão de comunidades tradicionais. O estado busca solucionar esses problemas por meio de políticas de regularização fundiária, demarcação de terras indígenas e intensificação da fiscalização. No entanto, é necessária a participação conjunta do governo, sociedade civil e comunidades para garantir direitos territoriais, fortalecer a governança fundiária e promover práticas sustentáveis de uso da terra.";

    limpa();
}

